[Distribution]
Distribution=debian
Release=trixie

[Output]
Format=disk
ImageId=k8s-node

[Content]
Bootable=yes
KernelCommandLine=console=ttyS0,115200n8 console=tty0
Packages=
    systemd
    systemd-boot
    systemd-resolved
    linux-image-amd64
    openssh-server
    sudo
    iptables
    iproute2
    ca-certificates
    curl
    cloud-init
    cloud-guest-utils
    e2fsprogs
    jq
