apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-server-route
  namespace: argocd
  annotations:
    # After cluster-gateway (wave 2)
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://github.com/MoreShields/oasis-control
    path: control/argocd/server-route
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - ServerSideDiff=true
